allowed_metrics:
  - container_cpu_usage_seconds_total
  - container_memory_usage_bytes
  - container_fs_usage_bytes
  - container_network_receive_bytes_total
  - container_network_transmit_bytes_total
  - container_cpu_load_average_10s
