version: '3.8'

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"  # Expose cAdvisor on port 8080
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    devices:
      - "/dev/kmsg"
    privileged: true  # Needed for some metrics

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    hostname: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    pid: host
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'

  cadvisor_push:
    build: ./cadvisor_push
    hostname: cadvisor_push
    container_name: cadvisor_push
    environment:
      HOST: http://cadvisor:8080/metrics
      PUSHGW: http://130.188.160.11:8080/metrics/job/pushgateway
      HOSTNAME: waterverse.ouludatalab.fi
      INTERVAL: 15
    volumes:
      - "./config.yaml:/config.yaml"

  node_push:
    build: ./node_push
    hostname: node_push
    container_name: node_push
    environment:
      HOST: http://node-exporter:9100/metrics
      PUSHGW: http://130.188.160.11:8080/metrics/job/pushgateway
      HOSTNAME: waterverse.ouludatalab.fi
      INTERVAL: 15
    volumes:
      - "./config-node.yaml:/config.yaml"
