version: '3.8'

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"  # Expose cAdvisor on port 8080
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    devices:
      - "/dev/kmsg"
    privileged: true  # Needed for some metrics

  dcgm-exporter:
    image: nvcr.io/nvidia/k8s/dcgm-exporter:4.1.1-4.0.4-ubuntu22.04
    container_name: dcgm-exporter
    hostname: dcgm-exporter
    ports:
      - "9400:9400"
    cap_add:
      - SYS_ADMIN
    gpus: all
    restart: "always"

  cadvisor_push:
    build: ./cadvisor_push
    hostname: cadvisor_push
    container_name: cadvisor_push
    environment:
      HOST: http://cadvisor:8080/metrics
      PUSHGW: http://130.188.160.11:8080/metrics/job/pushgateway
      HOSTNAME: <hostname>
      INTERVAL: 15
    volumes:
      - "./config.yaml:/config.yaml"

  gpu_push:
    build: ./gpu_push
    hostname: gpu_push
    container_name: gpu_push
    environment:
      HOST: http://dcgm-exporter:9400/metrics
      PUSHGW: http://130.188.160.11:8080/metrics/job/pushgateway
      HOSTNAME: <hostname>
      INTERVAL: 15
    volumes:
      - "./config.yaml:/config.yaml"
